//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-558 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.05.04 at 11:39:52 AM EDT 
//


package com.example.consumingwebservice.wsdl;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="checkVenueMeetsRequirmentsReturn" type="{http://soapy1}VenueRequirementsResponse"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "checkVenueMeetsRequirmentsReturn"
})
@XmlRootElement(name = "checkVenueMeetsRequirmentsResponse")
public class CheckVenueMeetsRequirmentsResponse {

    @XmlElement(required = true)
    protected VenueRequirementsResponse checkVenueMeetsRequirmentsReturn;

    /**
     * Gets the value of the checkVenueMeetsRequirmentsReturn property.
     * 
     * @return
     *     possible object is
     *     {@link VenueRequirementsResponse }
     *     
     */
    public VenueRequirementsResponse getCheckVenueMeetsRequirmentsReturn() {
        return checkVenueMeetsRequirmentsReturn;
    }

    /**
     * Sets the value of the checkVenueMeetsRequirmentsReturn property.
     * 
     * @param value
     *     allowed object is
     *     {@link VenueRequirementsResponse }
     *     
     */
    public void setCheckVenueMeetsRequirmentsReturn(VenueRequirementsResponse value) {
        this.checkVenueMeetsRequirmentsReturn = value;
    }

}
