//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-558 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.05.04 at 11:39:52 AM EDT 
//


package com.example.consumingwebservice.wsdl;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for VenueRequirements complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="VenueRequirements">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="nameOfVenue" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="expectedNumberAttendees" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="largeScreenNeeded" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "VenueRequirements", propOrder = {
    "nameOfVenue",
    "expectedNumberAttendees",
    "largeScreenNeeded"
})
public class VenueRequirements {

    @XmlElement(required = true)
    protected String nameOfVenue;
    protected int expectedNumberAttendees;
    protected boolean largeScreenNeeded;

    /**
     * Gets the value of the nameOfVenue property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNameOfVenue() {
        return nameOfVenue;
    }

    /**
     * Sets the value of the nameOfVenue property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNameOfVenue(String value) {
        this.nameOfVenue = value;
    }

    /**
     * Gets the value of the expectedNumberAttendees property.
     * 
     */
    public int getExpectedNumberAttendees() {
        return expectedNumberAttendees;
    }

    /**
     * Sets the value of the expectedNumberAttendees property.
     * 
     */
    public void setExpectedNumberAttendees(int value) {
        this.expectedNumberAttendees = value;
    }

    /**
     * Gets the value of the largeScreenNeeded property.
     * 
     */
    public boolean isLargeScreenNeeded() {
        return largeScreenNeeded;
    }

    /**
     * Sets the value of the largeScreenNeeded property.
     * 
     */
    public void setLargeScreenNeeded(boolean value) {
        this.largeScreenNeeded = value;
    }

}
